### ISSUE TITLE
Fast Direction Change

### ISSUE THREAD

**Issue by etempm** [ponoor/Ponoor_PowerSTEP01_Library#1]
Hi, I am using yoru library with X-NUCLEO-IHM03A1 and arduino. I am developing motion simulator and already working with servos. Now I have 4.5 nm nema34 stepper and testing movements. Movement position comes from the game telemetry data. Most of time, new command is arriving before the previous movement complete. When command arrived I am using driver.goTo() command to direct new absolute position.  Example problem: 
driver.goTo(400) (1 turn in half step)
when position 200 new command is arriving to driver.goTo(100)
stepper goes to 190(example) 
it seams step loss but not !
after movement completed new command arrived driver.goTo(99)
now stepper goes exactly position 99 !

indeed, internal position counter seems works fine, no step loss. What can be cause of this?

**Comment by kanta** [comment]
@etempm Hi, sorry I haven't recognized you opened this issue since long time.

As the datasheet of PowerSTEP01 says, `goTo` command can be given only when the previous motion command as been completed (not in BUSY state).
And any attempts to perform a `goTo` command when a previous command is under execution (in BUSY state) causes the command to be ignored. Probably you sent a `softStop` command at the same time?

In this kind of configuration, I recommend to build a servo system based on `run` command.
